name: ACR build

on: [push]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Get code from the repository
      uses: actions/checkout@v1
      with:
        ref: main

    - name: Run unit tests
      run: dotnet test MyWebAppTests/*.csproj
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_NOLOGO: true

    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: 7f033906-4c18-4014-b2b7-d437a14968f8
        password: 28d03a22-16d9-47eb-81f3-6236e9d42ba6
        registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        path: .
        dockerfile: 'dockerfile'
        repository: 'AKSTest'
        push: true
